### ISSUE TITLE
Upgrade to egui 0.21

### ISSUE THREAD

**Issue by Kryptos-FR** [Hirtol/egui_memory_editor#8]
I noticed some commits in `master` branch about upgrading to egui v0.21 (194e9ad6bd51eed39707e9731db3cde24039691d).

It seems to work on my end building from `master`, though I also noticed that a piece of code was removed [examples/simple/frame_history.rs#L81-L98](https://github.com/Hirtol/egui_memory_editor/commit/194e9ad6bd51eed39707e9731db3cde24039691d#diff-48d7013577f847536644fb3a7b3b1e30383df2f8d852f8a6dff37dd792e4ff51L81-L98).

Is there anything we can do to help?

**Comment by Hirtol** [comment]
On my end I noticed that several things seemed broken/changed for the worse in the `0.21` update.
All running on the  `simple` example.

For example, cell editing no longer shows the text you put in, this cell should show an `E` at the moment:
![image](https://user-images.githubusercontent.com/55356909/228198595-bfe20b67-a8f9-482d-a617-72428186e57e.png)

There also seems to be a weird clipping issue due to the new update, extending past the top bar for any reason (more than 15 columns) makes egui clip all the content (without the top bar the whole ScrollArea seems to allocate no space at all and gets clipped?). Example below, notice how the ASCII display is cut off to only 3 characters:
![image](https://user-images.githubusercontent.com/55356909/228199141-e546df19-725c-4442-8576-85731a009342.png)

Everything else still seemed to work, but I found the clipping issue egregious enough to not push a new update to crates.io. Haven't looked much at it since (and couldn't find anything in the changelog mentioning clipping changes).

If you feel like looking at that issue I certainly wouldn't mind! It's the main blocker for a new release.

**Comment by Kryptos-FR** [comment]
For the first issue, it looks like something has changed around the layouting of characters or the default monospace font might have different properties.
Setting a value of `14` for the `desired_width` seems to *almost* fix it.

```diff
let response = ui.add(
    TextEdit::singleline(&mut frame_data.selected_edit_address_string)
-       .desired_width(6.0)
+       .desired_width(14.0)
        .font(options.memory_editor_text_style.clone())
        .hint_text(label_text)
        .id_source(frame_data.selected_edit_address),
```

Or it could be that there was an invisible carriage return character before, which is now taking zero space thanks to https://github.com/emilk/egui/pull/2452.

**Comment by Kryptos-FR** [comment]
For the scroll area, it is funny since the changelog mention that it should be *less aggressive about clipping its contents* but here it is exactly the opposite. This regression was likely introduced by https://github.com/emilk/egui/pull/2665. I guess you should open a bug in egui repo.

**Comment by Hirtol** [comment]
> For the first issue, it looks like something has changed around the layouting of characters or the default monospace font might have different properties. Setting a value of `14` for the `desired_width` seems to _almost_ fix it.
> 
> ```diff
> let response = ui.add(
>     TextEdit::singleline(&mut frame_data.selected_edit_address_string)
> -       .desired_width(6.0)
> +       .desired_width(14.0)
>         .font(options.memory_editor_text_style.clone())
>         .hint_text(label_text)
>         .id_source(frame_data.selected_edit_address),
> ```
> 
> Or it could be that there was an invisible carriage return character before, which is now taking zero space thanks to [emilk/egui#2452](https://github.com/emilk/egui/pull/2452).

That was indeed quite close! Turns out it's usually around `14.3`. I've updated it so that it's exactly the width of the other columns to prevent jitter. 

You still can't see the full value you're editing, but it's definitely better than before.

**Comment by Hirtol** [comment]
Never mind, the issue with the clipping was caused due to a change in `ui.min_rect()` which seems to have changed somewhat in `0.21`.

Changing the `shrink_window_ui` function to rely purely on previous frame data seems to have fixed that in this commit: https://github.com/Hirtol/egui_memory_editor/commit/dd402c7a6cfe0b4019452e08c6c598e325254141

I'll push a release tomorrow if there are no other issues.
Thanks for having a look!
